# Introduction

**Qu'est-ce que Climsoft** ?

[Climsoft](https://climsoft.org) est un système de gestion de base de données climatiques.
Il est composé d'une suite de logiciels conçus pour stocker de manière sécurisée et flexible des données climatiques et pour générer des informations et produits utiles à partir de ces dernières.
Climsoft peut être utilisé pour collecter, stocker et analyser des données climatiques provenant de différentes sources (stations classiques, automatiques, site de radiosondage etc.).
La version 4 de l'application cliente Climsoft a été élaborée sous Microsoft Visual Basic .NET et le moteur de stockage, c'est à dire la base de données par défaut est le logiciel MariaDB, un dérivé de MySQL, qui est un logiciel libre.

::: callout-note
## Note

-   **MariaDB Server** est un système de gestion de base de données relationnelle open source à usage général.
    C'est l'un des serveurs de base de données les plus populaires au monde, avec des utilisateurs notables tels que Wikipedia, WordPress.com et Google.
    MariaDB Server est publié sous la licence open source GPLv2 et est garanti de rester open source.
    Il est dérivé de MySQL.
    En savoir plus ici : <https://mariadb.org>.

-   **MySQL** est un système de gestion de bases de données relationnelles (SGBDR).
    Il est distribué sous une double licence GPL et propriétaire.
    Il fait partie des logiciels de gestion de base de données les plus utilisés au monde, autant par le grand public (applications web principalement) que par des professionnels, en concurrence avec Oracle, PostgreSQL et Microsoft SQL Server.
    En savoir plus ici : <https://www.mysql.com>

-   **Visual Basic** est un langage de programmation orienté objet développé par Microsoft.
    L\'utilisation de Visual Basic facilite la création d\'applications .NET de type sécurisé.
    Ce permet le développement rapide d'applications, la création d'interfaces utilisateur graphiques ainsi que l'accès aux bases de données.
    En savoir plus ici : <https://learn.microsoft.com/fr-fr/dotnet/visual-basic/>
:::

Le système Climsoft comprend entre autres:

1.  La base de données, qui contient les données climatiques de plusieurs stations dans une structure logique et structure logique et flexible ;

2.  Des formulaires de saisies, qui permet aux utilisateurs d'ajouter de nouvelles données à partir du clavier et ce de manière sûre et contrôlée.

3.  Des options permettant d'importer des données climatiques dans la base de données sous différents formats, par exemple des données provenant de stations météorologiques automatiques (SMA), CLICOM ASCII, NOAA GTS et des fichiers textes

4.  Des modules permettant exporter les données climatiques dans des formats prêts à être utilisés par de nombreuses applications climatiques à savoir [RCimDex](http://etccdi.pacificclimate.org/software.shtml), [Climate Predictability Tool](https://iri.columbia.edu/our-expertise/climate/tools/cpt/) (CPT), [GeoCLIM](https://earlywarning.usgs.gov/fews/software-tools/20), INSTAT ou [R-INSTAT](https://r-instat.org/team.html), [Climate Data Tool](https://iri.columbia.edu/our-expertise/climate/tools/cdt/), etc.;

5.  Des facilités de gestion d'images de documents papier (archives papiers) en soutien au programme de sauvetage de données de l'OMM ;

6.  Des options de contrôle de la qualité, et des modules de suivi, vérification des données insérées dans la base ;

7.  Un certain nombre de produits, des programmes d'application qui utilisent des sous-ensembles de données stockées dans la base de données pour produire des rapports utiles, des résumés, etc.

8.  Des fonctions de gestion du système pour gérer l'accès des utilisateurs, surveiller les opérations, d'administrer la base de données et d'adapter les fonctions du système aux besoins au niveau local.
